using NUnit.Framework;

namespace AoC.Year2025;

[TestFixture]
class Day07Test
{
	const string SampleInput1 =
		"""
		.......S.......
		...............
		.......^.......
		...............
		......^.^......
		...............
		.....^.^.^.....
		...............
		....^.^...^....
		...............
		...^.^...^.^...
		...............
		..^...^.....^..
		...............
		.^.^.^.^.^...^.
		...............
		""";

	[Test]
	public void SolvePart1() => Helper.ValidateSolution<Day07SolutionPart1>(
		expected: "21", input: SampleInput1);

	[Test]
	public void SolvePart2() => Helper.ValidateSolution<Day07SolutionPart2>(
		expected: "40", input: SampleInput1);
}
